# 地址服务配置
server:
  port: 9006

spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/elm_address?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8

# 地址服务特定配置
address:
  service:
    max-addresses-per-user: 10
    default-address-type: "HOME"
    geo-validation-enabled: true
    
# 地理编码服务配置
geocoding:
  api:
    provider: "baidu"
    key: "your-geocoding-api-key"
    timeout: 3000

# 熔断器配置
resilience4j:
  circuitbreaker:
    instances:
      address-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        sliding-window-size: 10 