# 生产环境配置
# 此配置文件在 prod 环境下会覆盖 application.yml 中的相同配置

# 生产环境数据库配置
spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/elm?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ${DB_USERNAME:elm_user}
    password: ${DB_PASSWORD:your_secure_password}
    # 生产环境数据库连接池配置
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      validation-timeout: 5000
      leak-detection-threshold: 30000

  # 生产环境RabbitMQ集群配置
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES:rabbitmq-node1:5672,rabbitmq-node2:5672,rabbitmq-node3:5672}
    username: ${RABBITMQ_USERNAME:elm_user}
    password: ${RABBITMQ_PASSWORD:your_secure_password}
    # 生产环境连接配置
    connection-timeout: 10000
    virtual-host: /elm
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 5
        multiplier: 2.0

# 生产环境日志配置
logging:
  level:
    root: WARN
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    com.elm: INFO
    # 生产环境关闭调试日志
    org.springframework.boot.autoconfigure: WARN
    org.apache.http: WARN
    org.springframework.cloud.openfeign: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"
  file:
    name: /var/log/elm/${spring.application.name}-prod.log
    max-size: 500MB
    max-history: 90
    total-size-cap: 10GB

# 生产环境Eureka集群配置
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVERS:http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/}
    # 生产环境较保守的配置
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
  instance:
    # 生产环境心跳配置
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: ${HOSTNAME:localhost}
    non-secure-port: ${server.port}

# 生产环境监控配置
management:
  endpoints:
    web:
      exposure:
        # 生产环境只暴露必要的端点
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  security:
    enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 生产环境安全配置
security:
  require-ssl: true
  headers:
    frame:
      deny: true
    content-type:
      nosniff: true

# 生产环境特定配置
environment:
  name: "production"
  debug: false
  features:
    sql-logging: false
    detailed-error-messages: false
    dev-tools: false
    
# 生产环境性能优化
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

# 生产环境熔断器配置（更严格的阈值）
resilience4j:
  circuitbreaker:
    instances:
      default:
        failure-rate-threshold: 30  # 生产环境更严格
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 30s  # 生产环境更长的等待时间 