# 开发环境配置
# 此配置文件在 dev 环境下会覆盖 application.yml 中的相同配置

# 开发环境数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2254600749@qq.com
    # 开发环境数据库连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # 开发环境RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 开发环境额外配置
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.0

# 开发环境日志配置
logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
    com.elm: DEBUG
    feign: DEBUG
    com.netflix.discovery: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"
  file:
    name: logs/elm-${spring.application.name}-dev.log
    max-size: 100MB
    max-history: 30

# 开发环境Eureka配置
eureka:
  client:
    # 开发环境更频繁的健康检查
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
  instance:
    # 开发环境更短的心跳间隔
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# 开发环境监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true

# 开发环境特定配置
environment:
  name: "development"
  debug: true
  features:
    sql-logging: true
    detailed-error-messages: true
    dev-tools: true 