# ELM微服务系统 - 全局默认配置
# 此配置文件包含所有微服务的公共配置

# 数据库公共配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8
    username: root
    password: 2254600749@qq.com
    
  # RabbitMQ公共配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 15000
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3

# MyBatis公共配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.elm.common.entity
  configuration:
    map-underscore-to-camel-case: true

# Eureka客户端公共配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
    # 健康检查
    healthcheck:
      enabled: true
    # 配置获取服务列表的间隔时间
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 配置心跳间隔
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

# Feign客户端公共配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: false

# 监控端点公共配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: true

# 日志配置
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
    com.elm: INFO
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用信息配置
info:
  app:
    name: ELM微服务系统
    version: 1.0.0
    description: 饿了么微服务系统配置中心 