# 商家服务专用配置
server:
  port: 8001

spring:
  application:
    name: business-service

# 商家服务特定配置
business:
  service:
    name: "商家服务"
    description: "提供商家信息管理、餐厅管理等功能"
    features:
      restaurant-management: true
      menu-management: true
      order-management: true

# 业务规则配置
rules:
  business:
    max-restaurants-per-business: 10
    min-delivery-fee: 0.0
    max-delivery-distance: 15.0 # 公里
    business-hours:
      default-open: "08:00"
      default-close: "22:00"
      
# 图片上传配置
upload:
  path: "/uploads/business/"
  max-file-size: 5MB
  allowed-types: 
    - jpg
    - jpeg
    - png
    - gif 