# 商家服务配置
server:
  port: 8002

spring:
  application:
    name: business-service
  datasource:
    url: jdbc:mysql://localhost:3306/elm_business?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  redis:
    database: 1  # 商家服务专用数据库

# 地图API配置
map:
  api:
    provider: "baidu"
    key: "your-map-api-key"
    timeout: 5000
    max-retry: 3

# 商家服务配置
business:
  service:
    max-distance-km: 10
    business-hours-start: "08:00"
    business-hours-end: "22:00"
    review-score-threshold: 3.5
    max-businesses-per-page: 20
    image-upload-path: /uploads/business/
    max-image-size: 10MB
  # 动态配置
  config:
    enable-auto-approval: false
    enable-review-system: true
    min-delivery-fee: 3.0
    max-delivery-distance: 15
    peak-hours:
      - "11:30-13:30"
      - "17:30-20:30" 