# 购物车服务专用配置
server:
  port: 8005

spring:
  application:
    name: cart-service

# 购物车服务特定配置
cart:
  service:
    name: "购物车服务"
    description: "提供购物车管理、商品添加删除等功能"
    features:
      cart-management: true
      item-operations: true
      price-calculation: true
      
# 购物车业务规则配置
rules:
  cart:
    max-items-per-cart: 30
    max-quantity-per-item: 99
    cart-expiry-hours: 24 # 购物车过期时间
    auto-clean-expired: true
    merge-same-items: true # 相同商品自动合并
    
# 价格计算配置
pricing:
  calculate-delivery-fee: true
  apply-discounts: true
  tax-calculation: false
  rounding-rule: "HALF_UP" # 四舍五入规则
  
# 缓存配置
cache:
  cart:
    ttl-minutes: 30 # 购物车缓存时间
    max-size: 1000
  pricing:
    ttl-minutes: 10 # 价格缓存时间
    
# 通知配置
notifications:
  cart-reminder: true
  price-change-alert: true
  item-unavailable-alert: true 