# 购物车服务配置
server:
  port: 8005

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/elm_cart?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  redis:
    database: 4  # 购物车服务专用数据库

# 购物车服务配置
cart:
  service:
    max-items: 99
    expire-hours: 24
    auto-clear-days: 7
    max-quantity-per-item: 20
    enable-cross-business-cart: false
    sync-interval-seconds: 30
  # 动态配置
  config:
    enable-recommendations: true
    enable-price-alerts: true
    max-saved-carts: 5
    auto-merge-similar-items: true
    discount:
      enable-bulk-discount: true
      bulk-threshold: 5
      bulk-discount-rate: 0.05 