# 消费者服务专用配置
server:
  port: 9001

spring:
  application:
    name: consumer-service
  cloud:
    loadbalancer:
      retry:
        enabled: true  # 启用重试机制
      cache:
        enabled: true  # 启用缓存
        ttl: 30000     # 缓存有效期(毫秒)

# 消费者服务特定配置
consumer:
  service:
    name: "消费者服务"
    description: "提供服务消费、负载均衡、熔断保护等功能"
    features:
      load-balancing: true
      circuit-breaker: true
      service-discovery: true
      retry-mechanism: true

# Feign客户端特定配置
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

# Ribbon负载均衡配置
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 5000
  MaxAutoRetries: 1           # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
  OkToRetryOnAllOperations: true

# Resilience4j 熔断器配置
resilience4j:
  circuitbreaker:
    instances:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        sliding-window-size: 10
      user-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s
        sliding-window-size: 8
      business-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s
        sliding-window-size: 8
      order-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s
        sliding-window-size: 8
      food-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s
        sliding-window-size: 8
      cart-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s
        sliding-window-size: 8
      address-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s
        sliding-window-size: 8
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
  timelimiter:
    instances:
      default:
        timeout-duration: 5s

# 服务调用配置
service:
  calls:
    timeout: 5000 # 服务调用超时时间
    max-retries: 3
    backoff-delay: 1000 # 重试间隔

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always 