# 食品服务配置
server:
  port: 9002

spring:
  application:
    name: food-service
  datasource:
    url: jdbc:mysql://localhost:3306/elm_food?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8

# 食品服务特定配置
food:
  service:
    max-items-per-page: 20
    image-upload-path: /uploads/food/
    max-image-size: 5MB
    allowed-image-types: jpg,jpeg,png,gif
    
# 缓存配置
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 2000ms 