# 食品服务配置
server:
  port: 8003

spring:
  application:
    name: food-service
  datasource:
    url: jdbc:mysql://localhost:3306/elm_food?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  redis:
    database: 2  # 食品服务专用数据库

# 食品服务配置
food:
  service:
    max-items-per-page: 20
    image-upload-path: /uploads/food/
    max-image-size: 5MB
    allowed-image-types: jpg,jpeg,png,gif,webp
    enable-watermark: true
    cache-expire-hours: 2
  # 动态配置
  config:
    enable-recommendation: true
    enable-nutrition-info: true
    max-categories: 50
    featured-foods-count: 10
    search:
      max-results: 100
      enable-fuzzy-search: true 