# 食品服务专用配置
server:
  port: 8004

spring:
  application:
    name: food-service

# 食品服务特定配置
food:
  service:
    name: "食品服务"
    description: "提供食品信息管理、分类管理等功能"
    features:
      food-management: true
      category-management: true
      inventory-tracking: true
      
# 食品业务规则配置
rules:
  food:
    max-categories: 20
    max-foods-per-category: 100
    price-precision: 2 # 价格小数位数
    inventory-alert-threshold: 10
    food-image-required: true
    
# 食品分类配置
categories:
  default:
    - "热销推荐"
    - "主食"
    - "小菜"
    - "汤类" 
    - "饮品"
    - "甜品"
    
# 图片上传配置
upload:
  food-images:
    path: "/uploads/food/"
    max-file-size: 2MB
    allowed-types:
      - jpg
      - jpeg
      - png
    max-images-per-food: 5
    
# 库存管理配置
inventory:
  auto-update: true
  low-stock-notification: true
  out-of-stock-auto-hide: true 