# 网关服务配置
server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/food/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000 