# 网关服务配置
server:
  port: 9000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/food/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: food-service
                fallbackUri: forward:/fallback/food
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/fallback/order
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: cart-service
                fallbackUri: forward:/fallback/cart
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: business-service
                fallbackUri: forward:/fallback/business
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: address-service
                fallbackUri: forward:/fallback/address
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: consumer-service
                fallbackUri: forward:/fallback/consumer
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000 
        pool:
          max-connections: 100
          max-idle-time: 30s

# 熔断器配置
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      user-service:
        base-config: default
      food-service:
        base-config: default
      order-service:
        base-config: default
      cart-service:
        base-config: default
      business-service:
        base-config: default
      address-service:
        base-config: default
      consumer-service:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
    instances:
      user-service:
        base-config: default
      food-service:
        base-config: default
      order-service:
        base-config: default
      cart-service:
        base-config: default
      business-service:
        base-config: default
      address-service:
        base-config: default
      consumer-service:
        base-config: default

# 动态配置
gateway:
  config:
    enable-rate-limiting: true
    enable-request-logging: true
    max-requests-per-second: 1000
    enable-ip-whitelist: false
    security:
      enable-jwt-validation: true
      jwt-secret: "gateway-jwt-secret-key-2024"
      excluded-paths:
        - "/user/login"
        - "/user/register"
        - "/actuator/**"
        - "/fallback/**" 