# 订单服务专用配置
server:
  port: 8003

spring:
  application:
    name: order-service

# 订单服务特定配置
order:
  service:
    name: "订单服务"
    description: "提供订单创建、状态管理、支付等功能"
    features:
      order-creation: true
      payment-processing: true
      order-tracking: true
      
# 订单业务规则配置
rules:
  order:
    max-items-per-order: 50
    order-timeout-minutes: 30
    auto-confirm-minutes: 15
    delivery-time-slots:
      - "立即送达"
      - "30分钟内"
      - "1小时内"
      - "2小时内"
    payment-methods:
      - "支付宝"
      - "微信支付"
      - "银行卡"
      - "现金"

# 支付配置
payment:
  timeout-seconds: 300 # 5分钟支付超时
  retry-attempts: 3
  
# 订单状态配置
status:
  flow:
    - "待支付"
    - "待确认"
    - "制作中"
    - "配送中"
    - "已完成"
    - "已取消" 