# 用户服务专用配置
server:
  port: 8002

spring:
  application:
    name: user-service

# 用户服务特定配置
user:
  service:
    name: "用户服务"
    description: "提供用户注册、登录、信息管理等功能"
    features:
      registration: true
      login: true
      profile-management: true
      
# 安全配置
security:
  jwt:
    secret: elm-user-service-secret-key
    expiration: 86400 # 24小时

# 业务配置
business:
  user:
    max-login-attempts: 5
    password-min-length: 6
    session-timeout: 1800 # 30分钟 